conversation/urls.py
from django.urls import path

from .views import new_conversation, inbox, detail

app_name = "conversation"

urlpatterns = [
  path("", inbox, name="inbox"),
  path('<int:convers_id>/', detail, name="detail"),
  path('new/<int:item_id>/', new_conversation, name="new"),
]

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm

app_name = "core"

urlpatterns = [
  path('', views.index, name="index"),
  path('contact/', views.contact, name="contact"),
  path('signup/', views.signup, name="signup"),
  path('login/', auth_views.LoginView.as_view(authentication_form=LoginForm, template_name='core/login.html'), name="login"),
]

dashboard/urls.py
from django.urls import path
from .views import index

app_name = "dashboard"

urlpatterns = [
  path("", index, name="index"),
]

item/urls.py
from django.urls import path
from .views import detail, new_item, delete, edit_item, items


app_name = 'item'
urlpatterns = [
  path("", items, name="items"),
  path('new/', new_item, name='new'),
  path('<int:pk>/', detail, name='detail'),
  path("delete/<int:pk>/", delete, name="delete"),
  path("edit/<int:pk>/", edit_item, name="edit"),
]

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):

  username = forms.CharField(widget=forms.TextInput(attrs={
    "placeholder": "Enter username",
    "class": "w-full py-4 px-6 rounded-xl",
  }))
  password = forms.CharField(widget=forms.PasswordInput(attrs={
    "placeholder": "Enter Password",
    "class": "w-full py-4 px-6 rounded-xl",
  }))



class SignupForm(UserCreationForm):

  username = forms.CharField(widget=forms.TextInput(attrs={
    "placeholder": "Enter username",
    "class": "w-full py-4 px-6 rounded-xl",
  }))
  email = forms.CharField(widget=forms.EmailInput(attrs={
    "placeholder": "Enter email",
    "class": "w-full py-4 px-6 rounded-xl",
  }))
  password1 = forms.CharField(widget=forms.PasswordInput(attrs={
    "placeholder": "Enter Password",
    "class": "w-full py-4 px-6 rounded-xl",
  }))
  password2 = forms.CharField(widget=forms.PasswordInput(attrs={
    "placeholder": "Confirm Password",
    "class": "w-full py-4 px-6 rounded-xl",
  }))

  class Meta:
    model = User
    fields = ('username', 'email', 'password1', 'password2')

core/views.py
from django.shortcuts import render, redirect
from item.models import Category, Item
from .forms import SignupForm

# Create your views here.
def index(request):
  categories = Category.objects.all()
  items = Item.objects.filter(is_sold=False)[:6]
  context = {'items': items, 'categories': categories}
  return render(request, 'core/index.html', context)

def contact(request):
  context = {}
  return render(request, 'core/contact.html', context)

def signup(request):
  if request.method == "POST":
    form = SignupForm(request.POST)
    if form.is_valid():
      form.save()
      return redirect("core:login")
  else:
    form = SignupForm()
  context = {"form": form}
  return render(request, 'core/signup.html', context)

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block document_name %}{% endblock %} | Puddle</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
  <nav class="px-6 py-6 flex justify-between items-center border-b border-gray-200">
    <a href="/" class="text-xl font-semibold">Puddle</a>

    <div class="space-x-6">
      <!--<a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500">New Item</a>-->
      <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500">New Item</a>
      <a href="{% url 'item:items' %}" class="text-lg font-semibold hover:text-gray-500">Browse</a>
      
      {% if request.user.is_authenticated %}
        <a href="{% url 'conversation:inbox' %}" 
          class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Inbox</a>
        <a href="{% url 'dashboard:index' %}"
          class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>
      {% else %}
        <a href="{% url 'core:signup' %}" 
          class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign Up</a>
        <a href="{% url 'core:login' %}"
          class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Login</a>
      {% endif %}
    </div>
  </nav>

  <div class="px-6 py-6">
    {% block content %}{% endblock %}
  </div>

  <footer class="px-6 py-6 flex justify-between bg-gray-800">
    <div class="w-2/3 pr-10">
      <h3 class="mb-5 font-semibold text-gray-400 ">About</h3>

      <p class="text-lg text-gray-500">Vivamus egestas eget odio non dapibus. Lorem ipsum dolor sit amet.</p>
    </div>
    <div class="w-1/3">
      <h3 class="mb-5 font-semibold text-gray-500">Menu</h3>

      <ul class="space-y-2">
        <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
        <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
        <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy Policy</a></li>
        <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Terms of Use</a></li>
      </ul>
    </div>
  </footer>
</body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block document_name %}Contact{% endblock %}

{% block content %}
  <h1>Contact Page</h1>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block document_name %}Front{% endblock %}

{% block content %}
  <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Newest Products</h2>

    <div class="grid grid-cols-3 gap-3">
      {% for item in items %}
        <div>
          <a href="{% url 'item:detail' item.id %}">
            <div>
              <img src="{{item.image.url}}" alt="{{item.name}}" class="rounded-t-xl">
            </div>

            <div class="p-6 bg-white rounded-b-xl">
              <h2 class="text-2xl">{{item.name}}</h2>
              <p class="text-gray-500">Price: {{item.price}}</p>
            </div>
          </a>
        </div>
      {% endfor %}
    </div>
  </div>

  <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Categories</h2>

    <div class="grid grid-cols-3 gap-3">
      {% for category in categories %}
        <div>
          <a href="#">
            <div class="p-6 bg-white rounded-b-xl">
              <h2 class="text-2xl">{{category.name}}</h2>
              <p class="text-gray-500">{{category.items.count}} items</p>
            </div>
          </a>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block document_name %}Login{% endblock %}

{% block content %}
  <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Login</h1>

    <form action="" method="POST">
      {% csrf_token %}

      {{form.non_field_errors}}

      {% for field in form %}
        <div class="mb-3">
          {% if field.errors %}
            {{field.errors}}
          {% endif %}
          <label for="{{field.name}}" class="inline-block mb-2">{{field.label}}</label><br>
          {{field}}
        </div>
      {% endfor %}

      <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">
        Login
      </button>
    </form>
  </div>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block document_name %}Sign Up{% endblock %}

{% block content %}
  <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign Up</h1>

    <form action="" method="POST">
      {% csrf_token %}

      {{form.non_field_errors}}

      {% for field in form %}
        <div class="mb-3">
          {% if field.errors %}
            {{field.errors}}
          {% endif %}
          <label for="{{field.name}}" class="inline-block mb-2">{{field.label}}</label><br>
          {{field}}
        </div>
      {% endfor %}

      <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">
        Submit
      </button>
    </form>
    <div class="m-8">Already has an account? 
      <a href="{% url 'core:login' %}"  class="py-4 px-8 text-lg bg-gray-500 hover:bg-gray-700 rounded-xl text-white">Login</a>
    </div>
  </div>
{% endblock %}