conversation/urls.py
from django.urls import path

from .views import new_conversation, inbox, detail

app_name = "conversation"

urlpatterns = [
  path("", inbox, name="inbox"),
  path('<int:convers_id>/', detail, name="detail"),
  path('new/<int:item_id>/', new_conversation, name="new"),
]

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm

app_name = "core"

urlpatterns = [
  path('', views.index, name="index"),
  path('contact/', views.contact, name="contact"),
  path('signup/', views.signup, name="signup"),
  path('login/', auth_views.LoginView.as_view(authentication_form=LoginForm, template_name='core/login.html'), name="login"),
]

item/urls.py
from django.urls import path
from .views import detail, new_item, delete, edit_item, items


app_name = 'item'
urlpatterns = [
  path("", items, name="items"),
  path('new/', new_item, name='new'),
  path('<int:pk>/', detail, name='detail'),
  path("delete/<int:pk>/", delete, name="delete"),
  path("edit/<int:pk>/", edit_item, name="edit"),
]

item/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):

  name = models.CharField(max_length=255)

  class Meta:
    ordering = ('name',)

  def __str__(self):
    return self.name
  
class Item(models.Model):

  category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='items')
  name = models.CharField(max_length=255)
  description = models.TextField(null=True, blank=True)
  price = models.FloatField()
  image = models.ImageField(upload_to='item_images', null=True, blank=True)
  is_sold = models.BooleanField(default=False)
  created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='items')
  created = models.DateTimeField(auto_now_add=True)

  class Meta:
    ordering = ('-created', 'category', 'name')

  def __str__(self):
    return f"{self.name} (in {self.category})"

item/forms.py
from django import forms
from .models import Item

class NewItemForm(forms.ModelForm):
  class Meta:
    model = Item
    fields = ('category', 'name', 'description', 'price', 'image', 'is_sold')

class EditItemForm(forms.ModelForm):
  class Meta:
    model = Item
    fields = ('name', 'description', 'price', 'image', 'is_sold')

item/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models.query import Q
from django.contrib.auth.decorators import login_required
from .models import Item, Category
from .forms import NewItemForm, EditItemForm
# Create your views here.


def items(request):
  query = request.GET.get("query", "")
  category_id = request.GET.get("category", "")
  if query:
    items = Item.objects.filter(
      Q(name__icontains=query) | 
      Q(description__icontains=query) | 
      Q(created_by__username__icontains=query)
    )
  elif category_id and category_id.isnumeric():
    items = Item.objects.filter(category__id=category_id)
    category_id = int(category_id)
  else:
    items = Item.objects.filter(is_sold=False)
  categories = Category.objects.all()
  context = {"items": items, "query": query, "categories": categories, "category_id": category_id}
  return render(request, 'item/items.html', context)

def detail(request, pk):
  item = get_object_or_404(Item, id=pk)
  current_user_conversation_id = ""
  if request.user.is_authenticated and request.user != item.created_by:
    existing_conversation = item.conversations.filter(participants__in=[request.user])
    if existing_conversation:
      current_user_conversation_id = existing_conversation[0].id

  related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(id=item.id)[:3]
  context = {"item": item, "related_items": related_items, "current_user_conversation_id": current_user_conversation_id}
  return render(request, 'item/detail.html', context)

@login_required
def new_item(request):
  form_type = "New Item"
  submit_button = "Create Item"
  if request.method == "POST":
    form = NewItemForm(request.POST, request.FILES)
    if form.is_valid():
      item = form.save(commit=False)
      item.created_by = request.user
      item.save()
      return redirect("item:detail", pk=item.id)
  else:
    form = NewItemForm()
  context = {"form": form, "form_type": form_type, 'submit_button': submit_button}
  return render(request, 'item/form.html', context)

@login_required
def edit_item(request, pk):
  form_type = "Edit Item"
  submit_button = "Update Item"
  item = get_object_or_404(Item, id=pk)
  if request.method == "POST":
    form = EditItemForm(data=request.POST, files=request.FILES, instance=item)
    if form.is_valid():
      form.save()
      return redirect("item:detail", pk=item.id)
  else:
    form = EditItemForm(instance=item)
  context = {"form": form, "form_type": form_type, 'submit_button': submit_button}
  return render(request, 'item/form.html', context)

@login_required
def delete(request, pk):
  item = get_object_or_404(Item, id=pk, created_by=request.user)
  if q := request.GET.get("q"):
    item.delete()
    return redirect("dashboard:index")
  context = {"item": item}
  return render(request, "item/delete.html", context)

item/templates/item/delete.html
{% extends 'core/base.html' %}

{% block document_name %}Delete {{item.name}}{% endblock %}

{% block content %}
  <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Delete {{item.name}}</h1>
    <p class="text-gray-500"><strong>Do you really want to delete {{item}}?</strong></p>

    <div class="space-x-6 items-center">
      <a href="{% url 'item:delete' item.id %}?q=yes" 
        class="inline-block mt-4 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-red-700">Yes</a>
      <a href="{{request.META.HTTP_REFERER}}"
        class="inline-block mt-4 px-6 py-3 text-lg font-semibold bg-green-500 text-white rounded-xl hover:bg-green-700">Cancel</a>
    </div>
  </div>
{% endblock %}

item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block document_name %}{{item.name}}{% endblock %}

{% block content %}
  <div class="grid grid-cols-5 gap-6">
    <div class="col-span-3">
      <img src="{{item.image.url}}" alt="{{item.name}}" class="rounded-xl">
    </div>

    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
      <h1 class="mb-6 text-3xl">{{item.name}}</h1>
      <p class="text-gray-500"><strong>Price: </strong>{{item.price}}</p>
      <p class="text-gray-500"><strong>Seller: </strong>{{item.created_by}}</p>

      {% if item.description %}
        <p class="text-gray-700">
          <strong class="text-gray-500">Description:</strong><br>
          {{item.description}}
        </p>
      {% endif %}

      {% if request.user == item.created_by %}
        <div class="mt-6 p-6 bg-white rounded-xl">
          {% if item.conversations.count > 0 %}
            <a href="{% url 'conversation:inbox' %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl">
              See Conversations
            </a>
          {% endif %}

          <a href="{% url 'item:edit' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-green-500 text-white rounded-xl">
            Edit
          </a>
          <a href="{% url 'item:delete' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">
            Delete
          </a>
        </div>
      {% else %}
        {% if current_user_conversation_id %}
          <a href="{% url 'conversation:detail' current_user_conversation_id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">
            Continue Conversation
          </a>
        {% else %}
          <a href="{% url 'conversation:new' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">
            Contact Seller
          </a>
        {% endif %}
      {% endif %}
    </div>
  </div>

  <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Related Items</h2>

    <div class="grid grid-cols-3 gap-3">
      {% for item in related_items %}
        <div>
          <a href="{% url 'item:detail' item.id %}">
            <div>
              <img src="{{item.image.url}}" alt="{{item.name}}" class="rounded-t-xl">
            </div>

            <div class="p-6 bg-white rounded-b-xl">
              <h2 class="text-2xl">{{item.name}}</h2>
              <p class="text-gray-500">Price: {{item.price}}</p>
            </div>
          </a>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

item/templates/item/form.html
{% extends 'core/base.html' %}

{% block document_name %}{{form_type}}{% endblock %}

{% block content %}
  <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">{{form_type}}</h1>

    <form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}

      {{form.non_field_errors}}

      {% for field in form %}
        <div class="mb-3">
          {% if field.errors %}
            {{field.errors}}
          {% endif %}
          <label for="{{field.name}}" class="inline-block mb-2">{{field.label}}</label>
          {% if field.name != "is_sold" %}<br>{% endif %}
          {{field}}
        </div>
      {% endfor %}

      <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">
        {{submit_button}}
      </button>
    </form>
  </div>
{% endblock %}

item/templates/item/items.html
{% extends 'core/base.html' %}

{% block document_name %}All Items{% endblock %}

{% block content %}
  <div class="pb-6 grid grid-cols-4 gap-4 bg-gray-100">
    <div class="col-span-1 mx-2">
      <form action="{% url 'item:items' %}" method="GET">
        <input type="text" class="mt-3 w-full py-4 px-6 border rounded-xl" value="{{query}}" name="query" placeholder="find a toy, clothe or furniture...">
        <button class="mt-2 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl">
          Search
        </button>
      </form>

      <hr class="my-6">

      <p class="font-semibold">Categories</p>
      <ul>
        {% for category in categories %}
          {% if category_id == category.id %}
            <li class="py-2 px-2 bg-gray-300 rounded-xl">
              <a href="{% url 'item:items' %}?category={{category.id}}">{{category.name}}</a>
            </li>
          {% else %}
          <li class="py-2 px-2 rounded-xl">
            <a href="{% url 'item:items' %}?category={{category.id}}">{{category.name}}</a>
          </li>
          {% endif %}
        {% endfor %}
      </ul>

      <hr class="my-6">

      <p class="font-semibold">Clear Filters</p>
      <ul>
        <li><a href="{% url 'item:items' %}" class="mt-2 py-4 px-8 inline-block bg-yellow-500 text-white rounded-xl">Clear</a></li>
      </ul>
    </div>

    <div class="col-span-3 m-2">
      <div class="grid grid-cols-3 gap-3">
        {% for item in items %}
          <div>
            <a href="{% url 'item:detail' item.id %}">
              <div>
                <img src="{{item.image.url}}" alt="{{item.name}}" class="rounded-t-xl">
              </div>
  
              <div class="p-6 bg-white rounded-b-xl">
                <h2 class="text-2xl">{{item.name}}</h2>
                <p class="text-gray-500">Price: {{item.price}}</p>
              </div>
            </a>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}